sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - PARSER=native
  - PARSER=lxml

addons:
  apt:
    packages:
    - unrar

matrix:
  include:
    - python: "3.6"
      env:
        - PARSER=native
        - VCR_RECORD_MODE=all
        - PYTEST_ADDOPTS="-m integration"
  allow_failures:
    - python: "3.6"
      env:
        - PARSER=native
        - VCR_RECORD_MODE=all
        - PYTEST_ADDOPTS="-m integration"

cache:
  directories:
    - $HOME/.cache/pip
    - tests/data/mkv

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -e .[test]
  - if [ $PARSER = "lxml" ]; then pip install lxml; fi
  - pip install coveralls

script: python setup.py test --addopts "--cov subliminal --verbose $PYTEST_ADDOPTS"

after_success: coveralls
