[default]
cache_dir = "~/.cache/subliminal"

[provider.opensubtitlescom]
username = "subliminal"
password = "subliminal"
apikey = "mij33pjc3kOlup1qOKxnWWxvle2kFbMH"

[provider.addic7ed]
username = "subliminal"
password = "subliminal"
timeout = 20

[refiner.omdb]
apikey = "44d5b275"

[refiner.tmdb]
apikey = "xxxxxxxxx"

[download]
provider = ["addic7ed", "opensubtitlescom", "opensubtitles"]
refiner = ["metadata", "hash", "omdb"]
ignore_refiner = ["tmdb"]
language = ["fr", "en", "pt-br"]
foreign_only = false
encoding = "utf-8"
min_score = 50
archives = true
verbose = 3
